name = "TreeContractor"
uuid = "9c73e9a1-f3ff-4299-8ff4-9ebd1df36108"
authors = ["nzy1997"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[compat]
LinearAlgebra = "1.11.0"
OMEinsum = "0.9.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
